### ISSUE TITLE
v1.2.2 build failed. 'single-line-log' should not be devDependencies.

### ISSUE THREAD

**Issue by dongsik-yoo** [s00d/webpack-progress-ora-plugin#1]
Thank you for your great plugin.

`"single-line-log"` should be in "dependencies" because it's required In progressBar.js
https://github.com/s00d/webpack-progress-ora-plugin/blob/0f429a56476f661510bd563f7fec0b175d876d0b/ProgressBar.js#L1-L3

https://github.com/s00d/webpack-progress-ora-plugin/blob/0f429a56476f661510bd563f7fec0b175d876d0b/package.json#L35-L39

The below is an error I got.
```bash
Error: Cannot find module 'single-line-log'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nhn/Source/dooray/task-tracker/src/main/webapp/client/bundles/node_modules/webpack-progress-ora-plugin/ProgressBar.js:1:76)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by s00d** [comment]
Thanks for the report — you were right.

This is fixed in **v2.0.0** (published on `master`):

- `single-line-log` is no longer used. It was abandoned (last release 2016), so the fallback progress bar now uses [`log-update`](https://github.com/sindresorhus/log-update), declared in **`dependencies`**.
- Runtime deps (`chalk`, `ora`, `log-update`) are bundled into `dist/` for reliable installs with `npm install --production`.
- Package metadata is linted with [publint](https://publint.dev) on publish.

Upgrade:

```bash
npm install webpack-progress-ora-plugin@^2.0.0
```

**Note:** v2 is a major release — TypeScript build, Node.js >= 20, webpack 5 only.

Sorry for the long wait, and thanks again for catching this.
